import React, { useState, useEffect } from 'react';
import { useParams, useLocation, Link } from 'react-router-dom';
import { motion } from 'motion/react';
import { ArrowLeft, Sparkles, BookOpen, TrendingUp, DollarSign, Briefcase, MessageSquare, CheckCircle2, Lightbulb, GraduationCap, Wrench, Layers, Users } from 'lucide-react';
import { Career } from '../types';
import { explainCareerFit, generateDetailedRoadmap } from '../services/geminiService';
import ReactMarkdown from 'react-markdown';

export default function CareerDetailPage() {
  const { id } = useParams();
  const location = useLocation();
  const userTraits = location.state?.traits;
  const passedCareer = location.state?.career;
  
  const [career, setCareer] = useState<Career | null>(passedCareer || null);
  const [explanation, setExplanation] = useState<string>("");
  const [roadmap, setRoadmap] = useState<string>("");
  const [loading, setLoading] = useState(!passedCareer);
  const [aiLoading, setAiLoading] = useState(false);

  useEffect(() => {
    if (!passedCareer) {
      fetch(`/api/career-details/${id}`)
        .then(res => res.json())
        .then(data => {
          setCareer(data);
          setLoading(false);
        });
    }
  }, [id, passedCareer]);

  useEffect(() => {
    if (career) {
      if (location.state?.isGenerated) {
        // If it was generated, we already have the roadmap in the career object
        setRoadmap(career.learning_roadmap.map((step, i) => `${i+1}. ${step}`).join('\n\n'));
        setExplanation("This career path was generated by our AI based on industry standards and current trends.");
      } else if (userTraits) {
        setAiLoading(true);
        Promise.all([
          explainCareerFit(career, userTraits),
          generateDetailedRoadmap(career)
        ]).then(([exp, road]) => {
          setExplanation(exp);
          setRoadmap(road);
          setAiLoading(false);
        });
      } else {
        // Just generate roadmap if no user traits (manual exploration)
        setAiLoading(true);
        generateDetailedRoadmap(career).then(road => {
          setRoadmap(road);
          setExplanation(`Explore the exciting world of ${career.career_name}. This field offers diverse opportunities and a promising future.`);
          setAiLoading(false);
        });
      }
    }
  }, [career, userTraits, location.state?.isGenerated]);

  if (loading) return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="animate-spin rounded-full h-12 w-12 border-t-2 border-b-2 border-emerald-600"></div>
    </div>
  );

  if (!career) return <div className="text-center py-20">Career not found.</div>;

  return (
    <div className="space-y-12 py-12 max-w-5xl mx-auto">
      <Link to="/results" className="inline-flex items-center text-stone-500 hover:text-stone-900 font-medium group">
        <ArrowLeft className="mr-2 w-4 h-4 group-hover:-translate-x-1 transition-transform" />
        Back to Results
      </Link>

      <header className="space-y-6">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
          <div className="space-y-4">
            <h1 className="text-5xl md:text-6xl font-bold tracking-tight text-stone-900">{career.career_name}</h1>
            <p className="text-xl text-stone-600 max-w-2xl leading-relaxed">{career.description}</p>
          </div>
          <Link 
            to="/chat" 
            state={{ career }}
            className="px-8 py-4 bg-emerald-600 text-white rounded-2xl font-bold hover:bg-emerald-700 transition-all shadow-lg flex items-center group"
          >
            <MessageSquare className="mr-2 w-5 h-5" />
            Ask AI Mentor
          </Link>
        </div>
      </header>

      <div className="grid md:grid-cols-3 gap-8">
        {/* Quick Stats */}
        <div className="md:col-span-1 space-y-6">
          <div className="bg-white border border-stone-200 rounded-3xl p-8 space-y-8 shadow-sm">
            <div className="space-y-4">
              <h3 className="text-sm font-bold uppercase tracking-widest text-stone-400 flex items-center">
                <DollarSign className="mr-2 w-4 h-4" />
                Salary Potential
              </h3>
              <div className="text-2xl font-bold text-stone-900">{career.salary_range}</div>
            </div>
            <div className="space-y-4">
              <h3 className="text-sm font-bold uppercase tracking-widest text-stone-400 flex items-center">
                <TrendingUp className="mr-2 w-4 h-4" />
                Future Demand
              </h3>
              <div className="text-2xl font-bold text-emerald-600">{career.future_demand}</div>
            </div>
            <div className="space-y-4">
              <h3 className="text-sm font-bold uppercase tracking-widest text-stone-400 flex items-center">
                <Briefcase className="mr-2 w-4 h-4" />
                Education Path
              </h3>
              <div className="text-lg font-semibold text-stone-700 leading-snug">{career.education_path}</div>
            </div>
          </div>

          <div className="bg-stone-900 rounded-3xl p-8 text-white space-y-6 shadow-xl shadow-stone-900/10">
            <h3 className="text-lg font-bold flex items-center">
              <CheckCircle2 className="mr-2 text-emerald-400 w-5 h-5" />
              Core Skills
            </h3>
            <div className="flex flex-wrap gap-2">
              {career.required_skills.map(skill => (
                <span key={skill} className="px-3 py-1.5 bg-white/10 rounded-lg text-sm font-medium border border-white/5">
                  {skill}
                </span>
              ))}
            </div>
          </div>
        </div>

        {/* AI Insights & Roadmap */}
        <div className="md:col-span-2 space-y-8">
          {/* Detailed Career Info (if available) */}
          {career.core_philosophy && (
            <section className="bg-white border border-stone-200 rounded-[2.5rem] p-10 md:p-12 shadow-sm space-y-12">
              <div className="space-y-4">
                <h2 className="text-2xl font-bold flex items-center text-stone-900">
                  <Lightbulb className="mr-3 text-amber-500 w-6 h-6" />
                  The Core Philosophy
                </h2>
                <p className="text-lg text-stone-600 leading-relaxed italic">
                  "{career.core_philosophy}"
                </p>
              </div>

              {career.curriculum && (
                <div className="space-y-6">
                  <h3 className="text-xl font-bold flex items-center text-stone-900">
                    <GraduationCap className="mr-3 text-blue-500 w-6 h-6" />
                    The Curriculum (What You Will Study)
                  </h3>
                  <div className="grid sm:grid-cols-2 gap-4">
                    {career.curriculum.map((item, idx) => (
                      <div key={idx} className="p-4 bg-stone-50 rounded-2xl border border-stone-100">
                        <div className="font-bold text-stone-900 mb-1">{item.split(':')[0]}</div>
                        <div className="text-sm text-stone-600">{item.split(':')[1]}</div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {career.tools_software && (
                <div className="space-y-6">
                  <h3 className="text-xl font-bold flex items-center text-stone-900">
                    <Wrench className="mr-3 text-stone-500 w-6 h-6" />
                    Essential Tools & Software
                  </h3>
                  <div className="flex flex-wrap gap-3">
                    {career.tools_software.map((tool, idx) => (
                      <span key={idx} className="px-4 py-2 bg-stone-100 text-stone-700 rounded-xl font-medium text-sm">
                        {tool}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {career.sub_disciplines && (
                <div className="space-y-6">
                  <h3 className="text-xl font-bold flex items-center text-stone-900">
                    <Layers className="mr-3 text-purple-500 w-6 h-6" />
                    Major Sub-disciplines
                  </h3>
                  <ul className="grid sm:grid-cols-2 gap-3">
                    {career.sub_disciplines.map((sub, idx) => (
                      <li key={idx} className="flex items-center text-stone-600">
                        <div className="w-1.5 h-1.5 bg-purple-400 rounded-full mr-3" />
                        {sub}
                      </li>
                    ))}
                  </ul>
                </div>
              )}

              {career.student_reality && (
                <div className="p-8 bg-amber-50 rounded-3xl border border-amber-100 space-y-4">
                  <h3 className="text-xl font-bold flex items-center text-amber-900">
                    <Users className="mr-3 text-amber-600 w-6 h-6" />
                    The Student Reality
                  </h3>
                  <p className="text-amber-900/80 leading-relaxed">
                    {career.student_reality}
                  </p>
                </div>
              )}
            </section>
          )}

          {/* AI Fit Explanation */}
          <section className="bg-white border border-stone-200 rounded-[2.5rem] p-10 md:p-12 shadow-sm relative overflow-hidden">
            <div className="absolute top-0 right-0 p-6 opacity-10">
              <Sparkles className="w-24 h-24 text-emerald-600" />
            </div>
            <h2 className="text-2xl font-bold mb-8 flex items-center">
              <Sparkles className="mr-3 text-emerald-600 w-6 h-6" />
              Why This Fits You
            </h2>
            {aiLoading ? (
              <div className="space-y-4 animate-pulse">
                <div className="h-4 bg-stone-100 rounded w-3/4" />
                <div className="h-4 bg-stone-100 rounded w-full" />
                <div className="h-4 bg-stone-100 rounded w-5/6" />
              </div>
            ) : (
              <div className="prose prose-stone prose-lg max-w-none text-stone-600 leading-relaxed">
                <ReactMarkdown>{explanation}</ReactMarkdown>
              </div>
            )}
          </section>

          {/* Learning Roadmap */}
          <section className="bg-emerald-50/50 border border-emerald-100 rounded-[2.5rem] p-10 md:p-12 shadow-sm">
            <h2 className="text-2xl font-bold mb-8 flex items-center text-emerald-900">
              <BookOpen className="mr-3 text-emerald-600 w-6 h-6" />
              Your Learning Roadmap
            </h2>
            {aiLoading ? (
              <div className="space-y-4 animate-pulse">
                <div className="h-4 bg-emerald-100/50 rounded w-3/4" />
                <div className="h-4 bg-emerald-100/50 rounded w-full" />
                <div className="h-4 bg-emerald-100/50 rounded w-5/6" />
              </div>
            ) : (
              <div className="prose prose-emerald prose-lg max-w-none text-emerald-900/80 leading-relaxed">
                <ReactMarkdown>{roadmap}</ReactMarkdown>
              </div>
            )}
          </section>
        </div>
      </div>
    </div>
  );
}
